import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
import React from "react";

export default function RootLayout({ children }) {
  return (
    <div>
      <header>
        <h1>MFSemi LLC</h1>
      </header>
      <main>{children}</main>
      <footer>
        <p>© 2025 MFSemi LLC. All rights reserved.</p>
      </footer>
    </div>
  );
}
